name: Code
description: File a bug report
labels: [ "bug" ]
title: 'Bug: '

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Code Issues are reserved for real, reproducible pagy bug. If you are not sure it's a bug, please ask in the 
        [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a) discussion area. 
        
        By following the steps below you will either solve your problem or ensure that it's a real reproducible bug to fix.

  - type: checkboxes
    id: prereq
    attributes:
      label: Before submitting...
      options:
        - label: I upgraded to the latest version of pagy
          required: true
        - label: I searched through the [Documentation](https://ddnexus.github.io/pagy/)
          required: true
        - label: I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
          required: true
        - label: I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)
          required: true

  - type: checkboxes
    id: support
    attributes:
      label: I am providing...
      description: |
        ...at least one of the following code supports reproducing the issue:
      options:
        - label: |
            Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console)
        - label: |
            Plain ruby file that can run as `ruby my-problem.rb`
        - label: |
            Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
        - label: |
            Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
        - label: |
            Link of my own branch forked from pagy, which contains an added test file
        - label: |
            Link of my own branch forked from [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)
        - label: |
            A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please, describe the issue...
    validations:
      required: true
